image_vis:
  - evi

# The regions to process (start, end)
regions:  
  - 000002
  - 000003
 

# The region file path
region_id_file: !!null
# /home/ubuntu/ym_field_boundaries/regions.csv


years:
  - 2022
  - 2023

# predict_year: 2021
# Start and end date for prediction
# Set as !!null to use dates from filenames. However, it is recommended
# to set these dates to avoid unexpected date inclusions.
# start_date: 01-01
# end_date: 12-30

lc_path: !!null


 

 